### ISSUE TITLE
simpleeval not defined 

### ISSUE THREAD

**Issue by VinsiGit** [LucianoCirino/efficiency-nodes-comfyui#79]
I'm using version 1.74
I get this error when using the evaluate nodes:

Error occurred when executing Evaluate Strings:

name 'simpleeval' is not defined

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 2873, in evaluate
functions = simpleeval.DEFAULT_FUNCTIONS.copy()

and

Error occurred when executing Evaluate Floats:

name 'simpleeval' is not defined

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 2841, in evaluate
result = simpleeval.simple_eval(python_expression, names={'a': a, 'b': b, 'c': c})

**Comment by LucianoCirino** [comment]
@VinsiGit 

I broke all of the simpleeval nodes because accidently i removed the line "from simpleeval import simple_eval" from "efficiency_nodes.py".

I just fixed this issue with the below commit.
https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/80/commits/e2e9c6bf334d2f0b5536da25a4fe8b52811fba80

Please update and try again. I apologize for the mistake.

**Comment by VinsiGit** [comment]
np mate thank you very much for the quick fix

**Comment by Eagle07-Sudo** [comment]
Did it work? For me, the problem persists even after the update, and I'm encountering another error:
```
Error occurred when executing KSampler:

list index out of range
```

**Comment by VinsiGit** [comment]
(closed it too early) I thought it would fix it but I still get the same error name 'simpleeval' is not defined. Its as if it can't the simpleeval even thought Y installed it.

**Comment by LucianoCirino** [comment]
> 

Could you please send me the error so I can diagnose?

**Comment by VinsiGit** [comment]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 2876, in evaluate
    functions = simpleeval.DEFAULT_FUNCTIONS.copy()
NameError: name 'simpleeval' is not defined


![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/40694625/ebc5d7f6-c017-4fd9-b049-e6e5f3a25310)

**Comment by LucianoCirino** [comment]
Okay I see issue.

In all my simpleeval calls I reference the package itself and not the specific simple_eval() function.

so...

```
from simpleeval import simple_eval
```

should be

```
import simpleeval
```

Please update and try again :) https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/81/commits/204dcc4204c309ab3aeb36ffdf4fbe54e5caf491

**Comment by VinsiGit** [comment]
It works now, thanks ;)
_also thx for the fast reply_
